### ISSUE TITLE
problemas con las licencias

### ISSUE THREAD

**Issue by pipinffd** [carlosaaraujo/esx_weaponshop#1]
hola quiero comprar la licencia y no me la da y me salta este error

Hi, I want to buy the license and he won't give it to me and I get  #this [error[](url)](ur
![sadasadsadsasad](https://user-images.githubusercontent.com/90886439/133723837-f83363bd-17a1-4062-9aa5-dfd8479ffb8a.PNG)
l)

**Comment by timmaia** [comment]
which version of "es_extended" you using?

**Comment by timmaia** [comment]
I've been testing it on v1-final and esx-legacy and it's working.
