### ISSUE TITLE
Blip Problem 

### ISSUE THREAD

**Issue by miwi-fbsd** [carlosaaraujo/esx_weaponshop#2]
Hey,

First of all thanks for the nice script, I found a small issue with the blips as you can see below on the screenshot it seems duplicate the blip, one it shows the weapon only and i can select 8 of them, but below is the Ammo Nation Blip, any idea how i can fix it?

- [ ]
![20211223121647_1](https://user-images.githubusercontent.com/6657176/147187240-34074683-56a4-4bea-98bc-5ffe566b58de.jpg)
 

Thx.

**Comment by carlosaaraujo** [comment]
I'm glad you liked it. I did some tests here and your problem did not occur to me.
![image](https://user-images.githubusercontent.com/46418534/147277075-8cca8f4c-4b59-44a2-adc4-3aa908a7bf45.png)
